### ISSUE TITLE
ยอดยกมา ไม่แสดงในเมนูรายงาน

### ISSUE THREAD

**Issue by joomlacorner** [goragod/omsin#1]
ยอดยกมาที่กรอกตั้งต้นตอนสร้างบัญชี ไม่แสดงใน เมนู เครื่องมือ->รายงาน
แต่แสดงในเมนู  เครื่องมือ->ค้นหา ครับ
![screenshot-localhost 8888 2017-06-04 18-14-59](https://cloud.githubusercontent.com/assets/144291/26761045/5cbf2d50-4952-11e7-82b8-b18154890e2b.png)
![screenshot-localhost 8888 2017-06-04 18-17-29](https://cloud.githubusercontent.com/assets/144291/26761044/5cb46cb2-4952-11e7-838b-ba991500b85f.png)

**Comment by goragod** [comment]
ถูกต้องแล้วครับ ผมออกแบบแบบนั้นเอง

เนื่องจากรายการสรุปรายรับรายจ่าย ผมต้องการให้เห็นภาพรวมเฉพาะยอดเงินที่เคลื่อนไหวจริงๆ ผมเลยจำกัดให้แสดงเฉพาะรายการที่เคลื่อนไหว เข้า-ออก จริงๆเท่านั้น

ซึ่งจริงๆผมก็เคยใส่ไปแล้ว แต่มันทำให้ยอดมันสูงเกินจริง ยากต่อการทำความเข้าใจ ว่า เรามีรายรัย-รายจ่าย ที่แท้จริงเป็นเช่นไร ครับ

ในกรณีที่ต้องการดูแบบละเอียดทุกรายการ ต้องไปดูที่รายงานที่กำหนดเองครับ

**Comment by joomlacorner** [comment]
เพิ่งสังเกตเห็นว่า เมนู สรุป รายรับ-รายจ่าย วันนี้   กับเมนู  รายงาน เป็น report เดียวกัน  
ตอนแรกคิดว่า เมนู รายรับ รายจ่ายวันนี้ กับ รายงาน จะมีความละเอียดต่างกันครับผม   ถ้าออกแบบไว้แบบนี้ก็ ok ครับ
